apiVersion: v1
kind: Namespace
metadata:
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-demo
  namespace: demoapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-demo
  template:
    metadata:
      labels:
        app: ingress-demo
    spec:
      containers:
      - name: ingress-demo
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "AKS Ingress Demo"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-demo
  namespace: demoapp  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ingress-demo

---
apiVersion: v1
kind: Namespace
metadata:
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: demoapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: demoapp  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demoapp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: aks-helloworld
              servicePort: 80
          - path: /demo(/|$)(.*)
            backend:
              serviceName: ingress-demo
              servicePort: 80
                